
sudo: no
dist: bionic
addons:
  postgresql: "9.5"
language: python
python:
  - "3.6"
env:
  - TOXENV=py35-tests
  - TOXENV=py35-flake8
  - TOXENV=py35-isort
install:
  - pip install -r requirements.txt
script:
  - python manage.py test